### ISSUE TITLE
How Send MO SMS from Jasmin SMPP Server

### ISSUE THREAD

**Issue by bandiphani** [jookies/jasmin#1013]
Hi All,

How to send MO-SMS from Jasmin SMPP Server.
 
Use Case:
One of our SMSC Vendor connected as Client to JASMIN SMPP Server with user Test1. Now we need to send MO SMS to SMSC Vendor through user Test1. How to fulfill this use case in Jasmin.  

Thanks & Regards,
Phani.

**Comment by farirat** [comment]
What pdu you using for MO flow: **deliver_sm** or **submit_sm** ?

**Comment by volga629-1** [comment]
That exactly what  issue I have
We get  submit_sm in MO 

```
PDU [command: CommandId.submit_sm, sequence_number: 17139, command_status: CommandStatus.ESME_ROK
```

Use case 

Some  upstream providers are not  allowing inbound SMPP connection ( security ) hence  they ask bind to Jasmin SMPP server 


```
                                                MO (Active binds: CommandId.bind_transceiver: 1)
SIP SERVER ( SMPP Client ) -----> Jasmin SMPP Server <----------Active binds: CommandId.bind_transceiver: 1------ Upstream Provider  


```

Because **transceiver: 1**  I should be able send messages both direction , but can't figure out routing rules if it possible.

In general it should be possible by introducing  traffic tagging.


Example:

Jasmin SMPP Server  have 10 active binds  as server  then possible create special MO route called TagMORoute which will allow set tag RED_LINE  on  2 from 10 binds.  
In addition will be possible set push connector which will determine which  provider (direction)  send message.
And last message is ACK for submitted  SM.

Flow 

```
Phone ---SMS--->SIP Server (client1) --- SMS ---> Jasmin SMPP Server  < ----- SMS ----Provider1---- Destination Number

``` 

Mo Rule  

```
Type=TagMORoute Tag=RED_LINE Member=client1,provider1 PushConnector=smpps(Provider1)

```
Hopefully idea is clear
