### ISSUE TITLE
save the tag in sms_logger

### ISSUE THREAD

**Issue by ChenYiHsiang** [jookies/jasmin#1021]
Hi, 
if we try the tag filters ,  use it in the interceptor and send sms. is it possible to save tag info with the sms log in sms_logger program?

**Comment by farirat** [comment]
since the sms_logger consumes messages directly from rabbitmq topics then it will only get Content objects holding smpp PDUs and some minimalistic metadata, the "routable" object holds the tagging data and is not exchanged over the rabbitmq broker.

You still can catch the routable inside the router (after interception occurs), the evalpy filter can be used for that, this is an example of logging the routable from within the filter ([here](https://docs.jasminsms.com/en/latest/faq/developers.html#how-to-log-events-inside-an-evalpyfilter)), you can adapt it to your needs.
