### ISSUE TITLE
Request to implement SMS-MT routing from smpps to httpc

### ISSUE THREAD

**Issue by texpert** [jookies/jasmin#125]
If it is no big effort, please!

**Comment by fourat** [comment]
As of now, routing is designed to deliver messages as below:

* smpps to smppc, smppc to smpps
* smppc to http, http to smppc

There's no

* smpps to http

Because it is a use case not often considered in a sms gateway, future plans are:

* Think of a http api for delivering bulks
* Implement submit_sm_multi in smppc and smpps

Future connectors to be designed are:

* Expose a ftp server to accept bulk messaging
* Expose ss7/sigtran connector

Any contrib/sponsoring are welcome to boost the project, and maybe an issue voting feature in github would help decide what priority to set.

**Comment by sah-anshu** [comment]
Hi zoufou

I think there shall be smppc/hhtpc to <any database> &&  <any database> to smpps/hhtp It will solve major integration.

**Comment by zoufou** [comment]
Non-confirmed feature, can be contributed.
