### ISSUE TITLE
Replicating each message attempt to MySQL

### ISSUE THREAD

**Issue by pguillem** [jookies/jasmin#145]
I assume the data is being stored on Redis.

1) Which file of jasmin would i have to modify (in python) so i could issue an insert statement each time a meesage is routed properly via MT? 

2) Which would be an appropiate file to trigger an SQL update upon receiving a DLR from the SMSC?

Would it be easier to do a trigger @ redis to then replicate message data to MySQL in another server?. I don´t even know if redis has triggers.

I want to do this because i fully understand how mysql works and actually SUCK at redis. By the way, my billing system works 100% with mysql.

**Comment by zoufou** [comment]
Hi !

Redis is used for saving temporary maps between message IDs in order to recognize the original sent message when a receipt is received, i understand you need to save messaging traffic with receipts in a data store, mysql or whatever .. this is pretty simple and Jasmin is already covering it:

Jasmin's messaging is done on top of a AMQP broker, MT,MO and receipts are exchanged by topics through RabbitMQ, if you want to take a real-time copy of the traffic you need to know where to plug your third party AMQP consumer, this document gives you the right map for your needs: http://docs.jasminsms.com/en/latest/messaging/index.html

So, if you want to get SubmitSm messages (MT Traffic) you need to consume from **submit.sm.*** or **submit.sm.resp.*** if you need to save the message when the ACK is received, for MO Traffic you'll need to consume from **deliver.sm.***, for receipts it will be **dlr_thrower.***.

I've been asked many times for the same requirements, i think it will be a good idea if you contribute to Jasmin with a sample third party script to demonstrate how to get Jasmin's message flows through these AMQP topics.

**Comment by pguillem** [comment]
Will do. I´ll gladly pop the code.
Thanks

**Comment by pguillem** [comment]
Hi @zoufou. Ok. I plugged a simple consumer to the queue and dumped the message via node.js amqp module. Just to try.

I realized you are messaging the whole object and, offcourse, the output is encoded as such.

in your queues/test directory, you use a class called Content.py (as an envelope i assume)... 

Question:
Is content.py being used in the test suitable for decoding your objects from the queue? What prototype should i use to decode the messages and get the relevant info? 

I really need to know the code a little better hehehe...  learning curve i presume.

Cheers

**Comment by pguillem** [comment]
Received message:

 �^Bcjasmin.vendor.smpp.pdu.operations
SubmitSM
q^@)�q^A}q^B(U^Fstatusq^Ccjasmin.vendor.enum
EnumValue
q^D)�q^E}q^F(U^D_keyq^GU^HESME_ROKq^HU  _enumtypeq      cjasmin.vendor.enum
Enum
q
)�q^K}q^L(U^PESME_RCANCELFAILq^Mh^D)�q^N}q^O(h^Gh^Mh    h^KU^F_indexq^PK^@ubU^XESME_RINVBCASTALIAS_NAMEq^Qh^D)�q^R}q^S(h^Gh^Qh  h^Kh^PK^BubU^NESME_RINVSYSIDq^Th^D)�q^U}q^V(h^Gh^$
ubU^RESME_RSERTYPDENIEDq&h^D)�q'}q((h^Gh&h      h^Kh^PK^EubU^OESME_RQUERYFAILq)h^D)�q*}q+(h^Gh)h        h^Kh^PK^MubU^WESME_RINVDSTADDRSUBUNITq,h^D)�q-}q.(h^Gh,h        h^Kh^PK^N$
)�q�}q�(hA(h�U^GLEVEL_1q�U^GLEVEL_2q�U^GLEVEL_3q�tq�h�]q�(h�h^D)�q�}q�(h^Gh�h   h�h^PK^Aubh^D)�q�}q�(h^Gh�h     h�h^PK^Bubh^D)�q�}q�(h^Gh�h     h�h^PK^Cubeh�h�h�h�h�h�h�h�ubh^PK$
3152222222q�U^Kprotocol_idq�K^@U^Sregistered_deliveryq�cjasmin.vendor.smpp.pdu.pdu_types

......goes on for 4 other pages..

**Comment by zoufou** [comment]
Okay i see the trouble you're in :)

Jasmin is exchanging python objects (SubmitSM, SubmitSMResp, DeliverSM objects ...) and they are pickled (serialized), i think it's not a good starting poing to be with nodejs.

Check this gist: https://gist.github.com/zoufou/5701d71bf6e404d17cb4
I've just written a basic consumer that can show you messages being exchanged in real time, run Jasmin, then run this script and make some SubmitSM traffic and you'll get the magic !

**Comment by pguillem** [comment]
You sir. Absolutely rock!

**Comment by pguillem** [comment]
I've added PySQLPool support to your script and created its own init.d in order to run it as a daemon.



I'll post the code tomorrow.
Best

Pedro

**Comment by pguillem** [comment]
I have added the PySQLPool code.to @zoufou ´s gist
https://gist.github.com/zoufou/5701d71bf6e404d17cb4

Here is the code to launch the consumer as a system Daemon in Debian/Ubuntu
https://gist.github.com/pguillem/19693defb3feb0c02fe7

1) create jasmind_consumer file in /etc/init.d/
2) chmod a+x
3) Modify the path and script name of your consumer in jasmind_consumer
4)  Remember to exec "update-rc.d jasmind_consumer defaults" in order to start at boot

Cheers
Pedro

**Comment by zoufou** [comment]
I've added your contrib to the F.A.Q: http://docs.jasminsms.com/en/stable/faq/index.html#how-to-log-messages-in-a-third-party-database

**Comment by prem-narain** [comment]
+1

**Comment by manojr2k** [comment]
will this method works for centos7 ?
can we log  credit deducted per sms as well ?

**Comment by geethupendra** [comment]
Hello 

I just tried to start the demon from (/etc/init.d/jasmind_consumer start)
No sign also check the status ..

Please explain (Remember to exec "update-rc.d jasmind_consumer defaults" in order to start at boot) how to do this step.

Thanks
Geeth
