### ISSUE TITLE
RHEL 7 rpm is asking for twisted packages although they are installed

### ISSUE THREAD

**Issue by zoufou** [jookies/jasmin#187]

**Comment by raamtg** [comment]
As a workaround, do this in the meantime.

[root@ip-172-31-43-24 tmp]# yumdownloader python-jasmin
Loaded plugins: amazon-id, rhui-lb
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
python-jasmin-0.6.35-1.el7.centos.noarch.rpm                                                                                                                                                                          | 1.3 MB  00:00:02     
[root@ip-172-31-43-24 tmp]#

[root@ip-172-31-43-24 tmp]# rpm -Uvh python-jasmin-0.6.35-1.el7.centos.noarch.rpm 
error: Failed dependencies:
        python-twisted-core is needed by python-jasmin-0.6.35-1.el7.centos.noarch
        python-twisted-web is needed by python-jasmin-0.6.35-1.el7.centos.noarch

[root@ip-172-31-43-24 tmp]# rpm -Uvh --nodeps python-jasmin-0.6.35-1.el7.centos.noarch.rpm 
Preparing...                          ################################# [100%]
jasmin:x:1001:
jasmin:x:1001:1001::/home/jasmin:/bin/bash
Updating / installing...
   1:python-jasmin-0.6.35-1.el7.centoswarning: /etc/jasmin/jasmin.cfg created as /etc/jasmin/jasmin.cfg.rpmnew
################################# [ 50%]
Cleaning up / removing...
   2:python-jasmin-0.6.26-1.el7.centos################################# [100%]
[root@ip-172-31-43-24 tmp]#

**Comment by zoufou** [comment]
@raamtg you can fix the packager directly by forking the  project used to package the rpms: https://github.com/jookies/jasmin-packager

It's using docker, you have to install it.
