### ISSUE TITLE
Problem in MO UTF-16BE messages

### ISSUE THREAD

**Issue by majidkabir** [jookies/jasmin#320]
I send "تست" by my mobile, when jasmin received this and sent it to http url it sent "%06%2A%063%06%2A", its incorrect, the correct value is "%06%2A%06%33%06%2A&", I checked it with my smpp client, the value that smsc sent to jasmin is "062A0633062A".
If its possible, you can add a setting to jasmin configs like 'MO-Content-UTF8' that if it set to true, content in MO messages convert from UTF-16BE to UTF8 in jasmin gateway(one of kannel features).

**Comment by majidkabir** [comment]
I checked it in python and the problem is urllib.urlencode!

**Comment by majidkabir** [comment]
I changed the line of 189 of throwers.py from 
RoutedDeliverSmContent.params['short_message']
to 
RoutedDeliverSmContent.params['short_message'].decode('utf-16-be').encode('utf-8')
and my problem solved

**Comment by zoufou** [comment]
Dear Majid, i've added tests in 12fd4452c5d0f3053116852c3cfab42a6bf922ee and tried to get them failed while throwing utf16 and utf8 strings of "تست" but in both tests, message were transmitted as is.

here's the utf16 test: https://github.com/zoufou/jasmin/blob/0.9b0/jasmin/routing/test/test_throwers_deliver_sm.py#L191
and the utf8 test:
https://github.com/zoufou/jasmin/blob/0.9b0/jasmin/routing/test/test_throwers_deliver_sm.py#L209

Can you please provide more data to help reproduce the issue ?

**Comment by majidkabir** [comment]
Hi Zoufou
Thank you for checking this issue, but the problem is when jasmin recived a UCS2 sms from smsc and want to send it to http connector!
urllib.urlencode() do not work correctly for UTF-16-BE in python.
the result for string "تست" must be "%06%2A%06%33%06%2A" but it returns "%06%2A%063%06%2A".
when this string recived in my java servlet the java URLDecoder cant decode it, for solving this problem I check the coding of sms and if the coding is utf-16-be I changed it to UTF-8 and then call urllib.urlencode().

**Comment by zoufou** [comment]
Can you please add the following lines just before what you did **throwers.py**:

    import binascii
    self.log.info('Debugging data, hexlified: %s, repr: %s' % (binascii.hexlify(RoutedDeliverSmContent.params['short_message']), repr(RoutedDeliverSmContent.params['short_message'])))
    self.log.info('Debugging data, complete pdu params: %s' % RoutedDeliverSmContent.params)

And share the outcome from the log file, please consider not sharing private data.

Thank you !

**Comment by majidkabir** [comment]
I add this lines to thrower.py but this logs does not show anything about my problem. 
I add this line after ''' encodedArgs = urllib.urlencode(args) '''
'''
self.log.info('Debugging data, encodedArgs: %s',encodedArgs)
'''

and now the log that show my problem is :
'''
2015-12-16 15:27:16 INFO     6152 Debugging data, hexlified: 062a0633062a, repr: '\x06*\x063\x06*'
2015-12-16 15:27:16 INFO     6152 Debugging data, complete pdu params: {'priority_flag': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd0b83e5610>, 0, 'LEVEL_0'), 'source_addr': '989218485229', 'protocol_id': 0, 'registered_delivery': RegisteredDelivery[receipt: NO_SMSC_DELIVERY_RECEIPT_REQUESTED, smeOriginatedAcks: set([]), intermediateNotification: False], 'replace_if_present_flag': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd0b83e5d10>, 0, 'DO_NOT_REPLACE'), 'dest_addr_ton': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd0b83e5f10>, 6, 'INTERNATIONAL'), 'source_addr_npi': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd0b83f20d0>, 9, 'ISDN'), 'schedule_delivery_time': None, 'dest_addr_npi': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd0b83f20d0>, 9, 'ISDN'), 'esm_class': EsmClass[mode: DEFAULT, type: DEFAULT, gsmFeatures: set([])], 'data_coding': DataCoding[scheme: DEFAULT, schemeData: UCS2], 'service_type': '1001', 'source_addr_ton': EnumValue(<jasmin.vendor.enum.Enum object at 0x7fd0b83e5f10>, 6, 'INTERNATIONAL'), 'sm_default_msg_id': 0, 'validity_period': None, 'destination_addr': '986715', 'short_message': '\x06*\x063\x06*'}
2015-12-16 15:27:16 INFO     6152 Debugging data, encodedArgs: priority=0&from=989218485229&origin-connector=RIGHTEL&coding=8&content=%06%2A%063%06%2A&to=986715&id=7f828a02-bb4c-47b3-9e6c-4cf7c2710215
'''
the problem is urllib.urlencode(), the content must be "%06%2A%06%33%06%2A" but it is "%06%2A%063%06%2A"

**Comment by zoufou** [comment]
Hi @majidkabir 
I've checked the issue and confirm there's an issue when urlencoding the data, the solution you found (decoding from utf16 and encoding to utf8) can only cover some of the cases, since you assumed that when coding = 8 (UCS2) the content is encoded in utf16, but that's not right in all situations, i can send ISO8859 using coding=8 as well ... in this case your solution will not work.

I guess the best thing is to send back the content in binary format when coding = 8, the receiver will find his way to decode the content since there's no way to know about it at Jasmin level, think about binary ringtone content or OTA configs, they use coding=8 but not utf16 or utf8, it's binary data, so my solution is to change the api to send the content in binary and keep the encoded content as well for backward compatibility, in other word, for your example "تست", you'll receive the followings:

* content = "%06%2A%063%06%2A"
* binary = "062A063062A"
* coding = 8

And i think it's even better to always send the binary parameter for all types of codings since it preserves the data as is.

What do you suggest ?

**Comment by majidkabir** [comment]
Hi @zoufou 
I think your solution is the best but maybe adding a config parameter in smppc for encoding MO messages to UTF-8 befor sending to http client in jasmin solved the problem of many users (ME :D).

Thanks

**Comment by zoufou** [comment]
Hi @majidkabir, that config must be per route and not on smppc level, because the connector can receive multiple types of encodings, you have to filter for the right type of traffic and apply on it a decoding to utf8, that's a pain to do on a route, so the right approaches are:

* On Jasmin level, you can use the interceptor and play with message content the way you like,
* On third party application level, you take the binary content and decode yourself

**Comment by synetalsolutions** [comment]
Hi 

I am trying to send a message using Jasmin SMS gateway and it is working fine but when  I am trying to send phasto or Arabic language it's not going.

Blank message received at client end
