### ISSUE TITLE
Client IP parameter

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#391]
Hello, developers!
I've got a question.

What are mandatory parameters for SMPP client?
According to the docs they are only login/password.
Why IP address is not required? According to the SMPP protocol IP is a mandatory parameter.

**Comment by raamtg** [comment]
Depends on what you are planning to do with smppc at the time of creation. To just create it, only cid is required. The rest will take defaults. however, to get it successfully working with minimal configurations, you will need to provide username, password, host, port and bind type (transceiver, receiver etc). Most, if not all the remaining defaults will work for any connection. The rest are merely turning parameters. Hope this helps.

**Comment by xamaxmacko** [comment]
These parameters are for the connections to SMSC only if I got this right. But I need to specify IP address for inbound connection, from ESME

**Comment by raamtg** [comment]
This is not something that is supported by Jasmin. If this is a prod environment, you would have to use iptables or a firewall in front of Jasmin to manage this. However since Jasmin only has one port allocated per ESME (user) - 2775 by default, you cannot specify a source address restriction per ESME. It will more likely be a whitelist of IP addresses that can access Jasmin as a whole. Then you use the bind credentials to authorize the account.
