### ISSUE TITLE
Hi how to send flash SMS.

### ISSUE THREAD

**Issue by anushakl** [jookies/jasmin#527]

**Comment by farirat** [comment]
Here's an example of intercepting message and setting the correct flags for flash, silent and OTA messages:

```
"""Playing with data_coding to send flash and hidden messages.
"""

from jasmin.vendor.smpp.pdu.pdu_types import DataCoding, DataCodingScheme, AddrSubunit

# Flash message
routable.pdu.params['data_coding'] = DataCoding(DataCodingScheme.RAW, 240)
# Silent message
routable.pdu.params['data_coding'] = DataCoding(DataCodingScheme.RAW, 192)
# Class 2 message (for OTA)
routable.pdu.params['dest_addr_subunit'] = AddrSubunit.SMART_CARD_1
```

**Comment by kevindiaz0322** [comment]
where it config that

**Comment by lauer** [comment]
@kevindiaz0322  and #525 

**Note: I had issues using the jasmin.vendor part, so use the following configuration instead.**

Create a file named flash_message.py on your Jasmin server with the following content:

## 1. Create the Flash Message Script

```python
from smpp.pdu.pdu_types import DataCoding, DataCodingScheme

# Flash message
routable.pdu.params['data_coding'] = DataCoding(DataCodingScheme.RAW, 240)
```

## 2. Create a Filter for Flash Messages

Before setting up an MT interceptor, create a filter so that only messages with the “flash” tag are intercepted. Open the Jasmin CLI and run:

```sh
jcli : filter -a
> type TagFilter
> tag flash
> fid flash_tag
> ok
```

## 3. Define the MT Interceptor

Now define the MT interceptor that uses the filter and the script you created. In the Jasmin CLI, execute:

```sh
jcli : mtinterceptor -a
> type StaticMTInterceptor
> filters flash_tag
> script python3(/etc/jasmin/store/flash_message.py)
> order 10
> ok
```

## 4. Persist the Configuration

Don’t forget to persist your changes with:

```sh
jcli : persist
```

## 5. Sending Flash Messages via HTTP API

When sending an SMS through the HTTP API, include the tag flash (i.e., tags=flash) in your API call to send the SMS as a flash message.

Read more here: https://docs.jasminsms.com/en/latest/interception/index.html
