### ISSUE TITLE
Configure resp-api port from jasmin.cfg

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#558]
I have located the command in jasmin-celery.service but can't locate port configuration.

ExecStart=/bin/sh -c "twistd -n --pidfile=/tmp/twistd-web-restapi.pid web --wsgi=jasmin.protocols.rest.api"

**Comment by farirat** [comment]
Since it's WSGI, you can use any compatible server and one of the best is Gunicorn so just replace **twistd ...** by this one:

> gunicorn -b 0.0.0.0:8080 jasmin.protocols.rest:api

I did not really find a way around **twistd** to set the bind port but anyway, gunicorn or cherrypy are better servers if you consider them for heavy production env, they were not packaged with jasmin because they will require extra dependencies ...
