### ISSUE TITLE
Custom src_ton per SMS

### ISSUE THREAD

**Issue by pgoergler** [jookies/jasmin#602]
Hello,

My SMPP provider allow us to customize the sender address (src_ton international or alphanumeric).

How can i send via HTTP api a SubmitSM with SRC_TON = 0 and another SubmitSM with SRC_TON=5 ?

I tried to add "src_ton" field in data send but it did not work.
```2017-07-25 11:03:34 ERROR    1 Error: 400: UrlArgsValidationError (Argument [src_ton] is unknown.)```

**Comment by farirat** [comment]
ton/npi params are not exposed over http api, you can use the interceptor to update those values.

**Comment by eno237** [comment]
Hello, 
I have the same problem and I need your help to build conditioning for setting src_ton on interceptor, so that it works automatically with src_ton 5 and 1.

src_ton-interceptor.py but doesn't work....

`
from jasmin.vendor.smpp.pdu.constants import addr_ton_name_map

if routable.pdu.params['source_addr'][:2] == "49" or routable.pdu.params['source_addr'][:3] == "+49":
   routable.pdu.params['source_addr_ton'] = addr_ton_name_map['INTERNATIONAL']
      
else:
   routable.pdu.params['source_addr_ton'] = addr_ton_name_map['ALPHANUMERIC']

`

hope to have helped!

Thanks
Eno

**Comment by tarikogut** [comment]
made 2 routing add filtering type submit with intecptor script.

2017-10-24 9:38 GMT+03:00 eno237 <notifications@github.com>:

**Comment by eno237** [comment]
i have tried it but doesn't even working.
is there any mistake ?

if routable.pdu.params['source_addr'][:2] == "49" or routable.pdu.params['source_addr'][:3] == "+49":
   routable.addTag(1)
else:
   routable.addTag(2)

**Comment by eno237** [comment]
with module is ok:  
"Select route (connector) based on source_addr. Filter tag 1 = international, tag 2 = alphanumeric"
from jasmin.vendor.smpp.pdu.pdu_types import AddrTon
if routable.pdu.params['source_addr'][:2] == "49" or routable.pdu.params['source_addr'][:3] == "+49":
   routable.addTag(1)   
else:
   routable.addTag(2)
