### ISSUE TITLE
Problems: with Spain symbols in sms, and from field

### ISSUE THREAD

**Issue by choodov** [jookies/jasmin#617]
Hello.

I have 2 questions:
1) I send HTTP request to jasmin like this:
http://<host:port>/send?username=xxx&password=xxxx&to=341111111&from=7777&coding=0&content=Hola! tu número...Tú!

but abonent got sms without 'ú'.
I tryed coding=0,2,6,8, but aways get "bad" result (without 'ú'; or Chinise symbols, etc).

How should I send request to jasmin, if my content in UTF-8, to get right sms?
2) what settings should I do to be able to send text in "from" field? Numbers are working, but text no. Fro example: if I send ...&from=Trulyalya... , abonent get sms from  "unknow number"

**Comment by jasonbingham** [comment]
1) Easiest way I have found to do this is coding=8 and utf-16 byte array of the message in hex-content.
http://host:port/send?username=xxx&password=xxxx&to=341111111&from=7777&coding=8&hex-content=0048006F006C006100210020007400750020006E00FA006D00650072006F002E002E002E005400FA0021
Have a look at this site if you want to convert text for testing https://r12a.github.io/apps/conversion/, you can do it programatically too.

2) Think from address is generally limited to 11 alpha numeric characters, no punctation, carrier and handset support varies. Make sure that the src_ton in the smpp connector to your upstream is set correctly too. (set to 5 for alphanumeric).

Jason

**Comment by choodov** [comment]
Thanks, Jason.
1. It works for me too. I used "UTF-16BE".
2. We used numbers

**Comment by aivisol** [comment]
I believe the problem still exists. If you try to send long message with UCS2 encoding, only first segment arrives correctly. The remaining ones are indeed "chinese". Looking at the pcap, I can see message is always split after 134 chars, instead of 67 as expected for UCS2. 
Now when I tried to localize the issue, I see that the logic is implemented in jasmin/protocols/smpp/operations.py , however when I try to modify there, the change does not affect the result. Is this the place to look for this problem? I think "if bits == 16:" statement is wrong here, you should not multiply message length by 2 because your message is already an unicode string. 
Please let me know if my assumption is correct.
