### ISSUE TITLE
re-send submit.sm PDU's

### ISSUE THREAD

**Issue by JFnine** [jookies/jasmin#654]
Good morning,

I’ve been checking the configuration of JasminSMPP to build it. In one of the URL’s – this one: jookies/jasmin#142 - I’ve found that was not posible to comunicate two SMPPclients by transforming deliver.sm to submit.sm because the standard didn’t allow that.

Then, from Jasmin platform, was wrote a basic scripted example to do this making a PDU and sending it to RabbitMQ, but the webpage - https://gist.github.com/zoufou/efc604070f34ef699c8b - seems that is not working anymore.

In the latest version of Jasmin, is still not posible to do this? Do I have to prepare some script to make it happen?

Anyway, what I'm trying to do is to connect a SMPP client to a SMPP server to send the SMS to the SMScenter. So, at first, I should be able to receive the petition of the SMPP client via PDU - submit.sm (deliver at my SMPP server) and, by creating a connector, re-send it to SMScenter.

Thanks in advance,

kind regards.

**Comment by farirat** [comment]
hello @JFnine, inversing deliver_sm to submit_sm is a usual case for operators in some countries of LATAM, there's a commercial project providing a sort of proxy in front of Jasmin acting like a pdu inversor to make Jasmin compliant with this non-standard smpp callflow (MT messages coming in deliver_sm pdus).

Please raise a demand on support@jasminsms.com

**Comment by JFnine** [comment]
hello @farirat , so I understand that there is no way to use the scripted example that you sent, is it?

I've sent an email to that direction but i havn't received a reply yet. 

Kind regards.

**Comment by farirat** [comment]
@JFnine is it JSD-258 ? please check for the update.

**Comment by JFnine** [comment]
Hi. 

I want that the server re-send the sms's that receives from a smpp client to the SMScenter.

**Comment by gamefia** [comment]
@JFnine were you able to did you find a workable solution?

**Comment by riceo** [comment]
For anyone that stumbles across this issue trying to solve the same problem, here is the solution to the opposite problem (submit_sm -> deliver_sm) with DLR support. 

 https://gist.github.com/riceo/80de777ca9209c86037159a7d6e6f27a

This will:

- Take an incoming `submit_sm`
- "convert it" to a `deliver_sm`
- Submit that to jasmin so that it can be used in regular MORouter Routes
- Submit a `deliver_sm` to jasmin with a tag (666 👻) attached so you can create an MORouter Route that filters on the tag and sends the DLR back to the originating user

I hope this saves someone the 40ish hours i've spent on this problem over the last few weeks! 🍻
