### ISSUE TITLE
Lock not acquired ! exiting

### ISSUE THREAD

**Issue by voicecomms** [jookies/jasmin#686]
Hello I have installed Jasmin on ubuntu after installation when I try to start jasmin I am getting the below error 
Lock not acquired ! exiting

Redif is already started on the same server 
please help.

Best Regards 
CJ

**Comment by tarikogut** [comment]
look tmp directory delete pids restart service.

voicecomms <notifications@github.com>, 9 Haz 2018 Cmt, 16:38 tarihinde şunu
yazdı:

**Comment by voicecomms** [comment]
Hello,

I am new to Jasmin , so what all services are needed to start i see interceptor and jasmin any other services apart from these? also any changes which needs to be done in jasmin.cfg file ?
Thanks in advance

Best Regards
CJ

**Comment by tarikogut** [comment]
add me skype tarikogut i will help you.

voicecomms <notifications@github.com>, 9 Haz 2018 Cmt, 17:19 tarihinde şunu
yazdı:

**Comment by sarita-panigrahi** [comment]
I am facing the same problem on Centos 7. It starts but gets deactivated automatically. Could you please help me out.
-----------------------------------------

 jasmind.service - Jasmin SMS Gateway
 Loaded: loaded (/usr/lib/systemd/system/jasmind.service; enabled; vendor preset: disabled)
 Active: inactive (dead) since Mon 2018-10-29 15:40:43 IST; 9s ago
 Process: 3826 ExecStart=/usr/bin/jasmind.py --username jcliadmin --password jclipwd (code=exited, status=0/SUCCESS)
 Main PID: 3826 (code=exited, status=0/SUCCESS)

Oct 29 15:40:38 localhost.localdomain systemd[1]: Started Jasmin SMS Gateway.
Oct 29 15:40:38 localhost.localdomain systemd[1]: Starting Jasmin SMS Gateway...
Oct 29 15:40:40 localhost.localdomain jasmind[3826]: :0: UserWarning: You do ...
Oct 29 15:40:43 localhost.localdomain jasmind[3826]: Lock not acquired ! exiting
Hint: Some lines were ellipsized, use -l to show in full.
[root@localhost ~]# sudo systemctl status jasmind -l
● jasmind.service - Jasmin SMS Gateway
   Loaded: loaded (/usr/lib/systemd/system/jasmind.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2018-10-29 15:40:43 IST; 22s ago
  Process: 3826 ExecStart=/usr/bin/jasmind.py --username jcliadmin --password jclipwd (code=exited, status=0/SUCCESS)
 Main PID: 3826 (code=exited, status=0/SUCCESS)

Oct 29 15:40:38 localhost.localdomain systemd[1]: Started Jasmin SMS Gateway.
Oct 29 15:40:38 localhost.localdomain systemd[1]: Starting Jasmin SMS Gateway...
Oct 29 15:40:40 localhost.localdomain jasmind[3826]: :0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Oct 29 15:40:43 localhost.localdomain jasmind[3826]: Lock not acquired ! exiting

**Comment by farirat** [comment]
Try to stop jasmin then delete /tmp/*.lock
then start again.

**Comment by sarita-panigrahi** [comment]
Worked like a charm!! Thanks a ton!!!

**Comment by Divyesh22598** [comment]
i have problem to start and enable service of jasmin.

**Failed to enable unit: Unit file jasmind.service does not exist.**
these error occurs how can fix it?
