### ISSUE TITLE
Unicode message using HTTP method

### ISSUE THREAD

**Issue by jamilkhogyanae** [jookies/jasmin#694]
Hi there,

We have installed jasmin sms api on our server, which is working fine for normal messages, but we are unable to send unicode messages (Pashto Language). If there is some way, please help us in this regard. 

@farirat please help in this matter. Thanks,

**Comment by robert1112** [comment]
@jamilkhogyanae  Did you solve the problem? Thanks.

**Comment by robert1112** [comment]
@jamilkhogyanae Thanks for confirmation. Hope @farirat can see this.

**Comment by farirat** [comment]
There's a simple example in the docs for sending UCS content: http://docs.jasminsms.com/en/latest/apis/ja-http/index.html#examples

Compared to Kannel, Jasmin's http api has a different approach when it comes to handling charset & encodings, while Kannel does a re-encoding job of your submitted content (that's why you need to indicate the charset and the coding params) Jasmin does not do any re-encoding, it will keep the content bytes as is putting the responsibility of the content on the user.

Long story made short, every byte you submit will delivered as is, for users who master the encoding dilemma they prefer the Jasmin way compared to Kannel.

More on that, Jasmin has a **hex-content** parameter (as a replacement to usual **content**), the hex-content provide an easy way to send hex strings like "0623" that will be sent to mobile as an arabic "أ" letter according to this: http://graphemica.com/%D8%A3
