### ISSUE TITLE
Rejecting SubmitSmPDU - using HTTP API

### ISSUE THREAD

**Issue by strat1959** [jookies/jasmin#721]
I'm new to jasmin and the whole sms gw and smsc. so, I'm trying to send(using a browser and http api) a MT SMS to my phone to test the smpp connection. I'm using jasmin as smpp client to connect to a smsc. I've followed the instruction so far. so, here is the issue.
my first issue was ESME_RINVSRCADR  which I've checked from messages.log. this was a smpp error and regards to Invalid source address. then I checked the jasmin docs and saw "Default source adress of each SMS-MT if not set while sending it, can be numeric or alphanumeric, when not defined it will take SMSC default". it was already not set. so, I've talked to smsc guys and asked for the GT number. when I set the GT number to src_addr of my smpp client conection. the second issue appeared. which has something to do with PDU. what should I do?
also when I use the browser to send the sms, the reply is successful.

first issue - messages.log = 2019-02-24 09:15:21 INFO     22375 SMS-MT [cid:samantel] [queue-msgid:65654cc9-3ad7-4f11-8431-810fd2c7c4b9] [status:ERROR/ESME_RINVSRCADR] [retry:False] [prio:0] [dlr:NO_SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:] [to:09XXXXXXXXX] [content:'hello-24022019-0915']
second issue - messages.log = 2019-02-24 09:48:36 CRITICAL 22375 Rejecting SubmitSmPDU[0bbdd713-17aa-4229-8d8d-34ec7bb7545a] through [cid:samantel] for an unknown error (<type 'exceptions.AttributeError'>): 'int' object has no attribute 'encode'

- smpp connection details : 
Session ref: 6
jcli : smppccm -s samantel
ripf 0
con_fail_delay 10
dlr_expiry 86400
coding 0
logrotate midnight
submit_throughput 110
elink_interval 30
bind_to 30
port 2776
con_fail_retry yes
password XXXXXXXX((smsc provided password)
src_addr XXXXXXXXXXXX(country code+msisdn=GT number that is assigned to my username by smsc co.)
bind_npi 0
addr_range None
dst_ton 1
res_to 120
def_msg_id 0
priority 0
con_loss_retry yes
username XXXXX(smsc provided username)
dst_npi 1
validity None
requeue_delay 120
host XXX.XXX.XXX.XXX(smsc ip address)
src_npi 1
trx_to 300
logfile //var/log/jasmin/default-samantel.log
systype
ssl no
cid samantel
loglevel 20
bind transceiver
proto_id None
dlr_msgid 0
con_loss_delay 10
bind_ton 0
pdu_red_to 10
src_ton 2

- smpp connection status 
#Connector id                        Service Session          Starts Stops
#samantel                            started BOUND_TRX        4      3

**Comment by mustafashujaie** [comment]
Getting the same error.

**Comment by mustafashujaie** [comment]
Ok, I found out what is going on in my case. @strat1959 Do you provide the source address when trying to send SMS? 

When setting up the connector I provided the source address which is a numerical short code XXX. When I tried to send a message through HTTP API, I was not providing the "from" parameter in the URL and because I have provided it in the JCLI. And get the following exception, and the SubmitPDU is rejected because of it:

`2019-04-23 05:08:48 CRITICAL 12280 Rejecting SubmitSmPDU[4ed2d373-7ea4-47dc-a87d-ebec374a9604] through [cid:AWCC_VAS_CON] for an unknown error (<type 'exceptions.AttributeError'>): 'int' object has no attribute 'encode'
`

After providing the shortcode in the "from" parameter in the URL, it works fine.

`curl http://127.0.0.1:1401/send? -d "username=username&password=password&to=XXXXX&from=123&content=hello"`

@strat1959  Can you please check if this is the case with you?

**Comment by strat1959** [comment]
@mustafashujaie 
yeah, I found out about it the same day when I checked the wiki page of http api, http request parameters section. I forgot to mention it here.
