### ISSUE TITLE
Failed to enable unit: Unit file jasmind.service does not exist.

### ISSUE THREAD

**Issue by Divyesh22598** [jookies/jasmin#723]
how to fix this error ??

**Comment by Samuelg17** [comment]
I was getting this error. The issue was I only setup the 'jasmin.service' file. Though you will need to setup all of the service files found 'https://github.com/jookies/jasmin/tree/master/misc/config/systemd'. This requires multiple services to start. Also make sure you do sudo systemctl daemon-reload before enabling jasmind.

**Comment by farirat** [comment]
What's your linux distro ?
