### ISSUE TITLE
Jasmin sms_logger.py MO message 

### ISSUE THREAD

**Issue by geethupendra** [jookies/jasmin#849]
Hello,

just setup Jasmin SMPP server and incoming and outgoing message working normally.

**message.log**
---------------------

> 2020-04-13 20:54:17 INFO     851 SMS-MT [cid:MO_smpp] [queue-msgid:20ac6ebb-135f-498e-b1d3-504545ca6873] [smpp-msgid:75257578064] [status:ESME_ROK] [prio:0] [dlr:NO_SMSC_DELIVERY_RECEIPT_REQUESTED] [validity:none] [from:New Mask] [to:94777123456] [content:'Teat MT']
> 
> 2020-04-13 20:54:51 INFO     851 SMS-MO [cid:MO_smpp] [queue-msgid:8f18c785-5be6-4e65-aeaf-e706e0874e29] [status:ESME_ROK] [prio:LEVEL_1] [validity:None] [from:94777123456] [to:89805] [content:'test MO']

---------------------

I just set up MySQL server for treating incoming and outgoing messages from using 
https://github.com/jookies/jasmin/blob/master/misc/scripts/sms_logger.py
scripts is only functioning outgoing SMS.. 

1. How do i code for incoming message
2. 59 and 60 lines on this scripts routing key show submit.sm and resp. in additionally added 
yield chan.queue_bind(queue="sms_logger_queue", exchange="messaging", routing_key='deliver_sm.*') . but it's not funtioning..

Thanks
Geeth

**Comment by farirat** [comment]
why are you looking for the sms_logger when you only need to handle mo traffic ? use the httpccm and morouter for that.

**Comment by mariusm30** [comment]
hi,

i've added https://github.com/jookies/jasmin/blob/master/misc/scripts/sms_logger.py as my default mtinterceptor. but the script only send the info to mysql when i manually start it (it also adds to mysql every sms that was sent before starting it). should i set it to work in daemon or i'm doing something wrong in setting it up in jasmin? 

PS: i'm a beginner in python & linux

thank you,
marius

**Comment by alihammoud90** [comment]
Any update on this issue?

I'm trying to log incoming messages and store them into database, same as the logic in **_sms_logger.py_**, but instead of inserting records only on _submit.sm.*_, I want to insert incoming messages also, regardless they were submitted again or not.

Sometimes _jasmin_ smppc connector receives an sms and rejects it for some reason (for example: **_insufficient balance_**), in this case _jasmin_ don't send _submit.sm_, so it can't be logged through **_sms_logger.py_** script

I tried to add a queue and add binding for most routing keys that includes "_deliver_" but still this queue didn't receive the message.

Any thoughts on this?

**Comment by magojr** [comment]
Not sure if it help you,
But if you want to log Mobile Originated messages, in my logger I've got also this row:
```
# Bind to deliver.sm.* to track received messages MO
yield chan.queue_bind(queue="sms_logger_queue", exchange="messaging", routing_key='deliver.sm.*')
```
Then, when you consume the queue you can check the key like this
```
msg = yield queue.get()
if msg.routing_key[:11] == 'deliver.sm.':
... 
```

As the sms_logger_queue is populated with sms sent (or received) I don't think you can found anything about sms blocked because of insufficient balance or other issue.  You probably should try with an interceptor.

**Comment by alihammoud90** [comment]
I already tried binding this key and consuming from the queue as I've mentioned, but no messages were sent to this queue, so I assumed on failed messages, it is not reaching deliver.sm, am I correct?

**Comment by magojr** [comment]
I don't use deliver.sm. route so I've not tried it but, when the message cannot be sent for any reason, it doesn't go into that queue, so I think the same logic is used for incoming messages.
So I think you're correct but i never tried it on MO messages. To be sure, let's wait some other reply on that.

**Comment by alihammoud90** [comment]
Yes I think so, thank you, will wait.
