### ISSUE TITLE
Throughput/multiprocessing

### ISSUE THREAD

**Issue by DanPhonovation** [jookies/jasmin#852]
I have Jasmin pointed at a multi node rabbitmq cluster while itself running on 8 cores, 8 gb of ram and an SSD backed datastore on an 36 core vmware machine. Plenty resources.

No matter what I do, I seem to cap out at about 200 and average ~140ish a second on a good second.

What is the preferred way to scale this? I've been used to kannel and with internal dlr storage we can average over 200+ there. I expected much greater performance out of something backed by rabbitmq. I love the API and ease of configuration + on the fly routing ability JasminSMS provides.

Would it be enough to vmware clone this machine and have it link up to the same rabbitmq cluster?

Its my understanding python is bound to one single core and there's no easy way to spread it across multiple cores. Cloning the machine might solve this.

Appreciate the help.

**Comment by magojr** [comment]
Hello,
I'm also interested about this topic, I installed Jasmin on a CentOS 7 box, working in a VmWare pool of resources. So I may use resources to have a big redis cluster or to have a Rabbit one or to have 10 little JAsmin boxex, all with redis and rabbit inside.  During heavy sending I can see erlang (RabbitMQ) using some CPUs at 30->60%, Redis using a low amount of CPU and a python process using only one CPU @ 80->100%. 
Performance get lower when both sms MT and DLR start to flow (so working on both direction).
I also tried to stresstest in a single direction a box with 16 cores and 32GB RAM in the same resource pool (sending to another jasmin box with the same config) and reached about 1000 SMS/sec without having DLR but in the real world speed very very lower. 
I think the bottleneck is more linked with the network rountrip time and response time to the upstream connector than a cpu/resources but analizyng the processes it seems that all the flow is limited from the python execution working on a single core so it may be iowait time that bring the core to 100% and it should be gret to know the best way to scale that.

Best approches may vary and may be different than usual so if any jasmin experienced person may, give us some adsvices it would be great for the wole community.
Thanks!

**Comment by DanPhonovation** [comment]
The reason is because python is bound to a single core by its very nature.

I successfully got Jasmin running with PyPy (A different implementation of Python promising speed boosts) but it did not seem to help.

In comparisonto magojr, I could barely get rabbitmq to register CPU usage. Consumption was often 20-40/sec which just seems awful.

I went around and gave all boxes extra cores just to be sure, same effect.

**Comment by SergeiFranco** [comment]
My **opinion** (I have nothing to do with the Jasmin dev team): 

This is an architectural problem that will never be resolved in the future without massive rewrite.
While the Jasmin is built on top of the asynchronous Twisted framework it will never scale as main process is running as a single process. Best way to scale this design is by having multiple containers (or VMs) running separate instances of Jasmin with the load balancer in front.

In addition to the problem of the single process the object overhead is enormous. The small PDUs are converted into a massive OOP convoluted hell, which are then pickled/unpickled while being queued and popped from rabbitmq multiple times.

I personally if were to design an SMS gateway, I would have built it on using python multiprocess (each message being individual process).

Ideally such application should have been build in erlang instead (since in Jasmin the core message handling is done via rabbitmq anyway). erlang was designed exactly for this type of workload.
