### ISSUE TITLE
How to store incoming sms to Mysql

### ISSUE THREAD

**Issue by shubhagrwl** [jookies/jasmin#871]
Hi,

Can you tell how can i store incoming sms to mysql for esme account that is connected to my smpp server.

Regards,
Shubham Agarwal

**Comment by farirat** [comment]
You can adapt this script to make it: https://github.com/jookies/jasmin/blob/master/misc/scripts/sms_logger.py

**Comment by ezechinwa** [comment]
You can use the interceptor script and hook it with a RestAPI that stores the messages

**Comment by magojr** [comment]
I tried the interceptor way and it was really slow because interceptor is sincronous.
So let's say that in mysql you can connect, insert data and disconnect in about 0,05sec, you are limiting the SMS sending to 20SMS/sec only for the mysql loggin part. In my specific case it was about 10SMS/sec instead of 50.
Using the approach suggested by farirat bring me to a non blocking logging because it consume (use) a rabbitMQ queue of the sent SMS in order to insert data, so you can manage it from another script without lock the sending operation, and also you can create a daemon that do it so 1 single connectione and disconnection and all INSERT needed in the middle. 
Hope it can help you

**Comment by magojr** [comment]
I just figured out i spoke about outgoing SMS and you asked for incoming but the concept is exactly the same, that queue (sms_logger_queue that need to be activated from the config file), is filled both with the outgoing and incoming messages and also with the DLR receipt (if your upstream provider send it). So you just need to switch on the message type as the sample script partially shows.

**Comment by ezechinwa** [comment]
How about have another RabbitMQ job which just listens for incoming SMS and performs the task in background without blocking Jasmin interception?

Example
1. Interceptor only sends message to be delivered to this queue with a flag called PENDING

2. This rabbitMQ server fetches all PENDING messages, inserts them mark them as Done and remove them from the Queue.


How does this sound? Just an idea might be a better way to implement this
.

**Comment by alihammoud90** [comment]
> I just figured out i spoke about outgoing SMS and you asked for incoming but the concept is exactly the same, that queue (sms_logger_queue that need to be activated from the config file), is filled both with the outgoing and incoming messages and also with the DLR receipt (if your upstream provider send it). So you just need to switch on the message type as the sample script partially shows.

@magojr can you explain more please? I tried the sms_logger script but didn't work for incoming SMS.

I added bindings for different routing keys including "deliver*", but didn't receive the SMS.

One use case is to insert to database failed/rejected SMS as well as success ones. So when an SMS is rejected, jasmin doesn't send submit.sm, it returns an error with one of the failed statuses.

**Comment by magojr** [comment]
I just replied here [issue 849](https://github.com/jookies/jasmin/issues/849)
