### ISSUE TITLE
No Error with batch request if "from" is missing

### ISSUE THREAD

**Issue by TW20-MH** [jookies/jasmin#887]
In the dokumentation about "batch messaging" [https://jasmin.readthedocs.io/en/latest/apis/rest/index.html?highlight=batch#send-multiple-messages](url) there is no "from" in the curl-request. if I do a batch curl request without the "from", I get back the following:
`{"data": {"batchId": "c37fe636-4eb8-4c33-a787-3479e0383c59", "messageCount": 1}}`
but no SMS is sent and I see the following error message in the log:
`ERROR    6399 Error: expected string or buffer`
The customer does not know whether the sending worked. Does it make sense to return an error message and not only a batchid? And maybe the documentation should be updated?

OS: Ubuntu 18.04
Jasmin-Version: 0.9.27

**Comment by farirat** [comment]
Hello

The "from" argument is optional as described in the http api documentation ([ref](https://jasmin.readthedocs.io/en/latest/apis/ja-http/index.html#http-request-parameters)), the error you are pointing out (expected string or buffer) is caused by another thing, please share more information, and expect an upgrade to 0.9.32 if python2 or 0.10.1 if python3.
