### ISSUE TITLE
singleshift locking shift support

### ISSUE THREAD

**Issue by tarikogut** [jookies/jasmin#907]
single shift locking shift support its possible ?

**Comment by farirat** [comment]
i'm not sure i've understood your question.

**Comment by hzcodertr** [comment]
National language shift tables

Shift tables allow characters relevant to other languages to be accessible
in SMS messages. Shift tables are selected using the User Data Header of an
SMS message. A *locking* shift table can be used to specify the table for
the whole message, whereas a *single* shift table can be used for an
individual character.

Shift tables exist for the following languages:

   - Spanish
   - Portuguese
   - Turkish
   - Urdu
   - Hindi
   - Bengali and Assamese
   - Punjabi
   - Gujarati
   - Oriya
   - Tamil
   - Telugu
   - Kannada
   - Malayalam


https://en.wikipedia.org/wiki/GSM_03.38

**Comment by farirat** [comment]
Are you looking for shifting in Jasmin ? if yes, then you can do it through the interceptor.

**Comment by hzcodertr** [comment]
no my mean in HTTP API support.

**Comment by hzcodertr** [comment]
National Language Shift
Along with the standard features of SMPP 3.4, we also provide the National Language Shift functionality which enables you to use special characters from language-specific character sets. National Language Shift Tables are character sets that are customized for specific characters according to the language, the list of supported languages can be found in the table below.

Using the extended character sets, you can send messages with language-specific special characters at the same price as standard GSM-7 messages. As an example, Turkish locking shift characters like ğ, Ğ, € are then at the cost of a single GSM-7 character⁠—there is no need for Unicode messages that would limit the total message amount down to 70 characters. Using the UDH we only reduce the message to 155 characters (since UDH takes up additional space in the message payload).

When a single shift of a particular character set is used, each extended letter will take up double space because an invisible space character has to be used to access the shift table.

For example, when using Spanish NLI Ú is only accessible in the single shift character set extension, which requires the use of an escape character. With each new single shift character introduced, the message length reduces by 1 respectively. This means in case there are 3 single shift characters, the default limit of 155 characters per NLI message is reduced to 152.

Example:

1B55 (1B is the escape character, 55 is Ú that is used from the extended character set)

Language selection is possible by using language identifiers within the UDH part of the message payload. The IEI (Information-Element-Identifier) specifies whether the single or locking shift will be used.

ESM class parameter, in this case, must be defined to 64.
Data coding values that can be used are 0 or 1.

**Comment by hzcodertr** [comment]
GSM 7-bit default alphabet and extension table of 3GPP TS 23.038 / GSM 03.38 support
