### ISSUE TITLE
PLEASE INFORM US ABOUT JASMIN SMS GATEWAY "LIMITS" SENDING SMS 

### ISSUE THREAD

**Issue by ChegMarcoADVANTECH** [jookies/jasmin#908]
Hello All.

**1 -** We want if Jasmin SMS Gateway has limits for sending SMS ???
**2 -** If so, how to define the limit for sending SMS in "**UNLIMITED**" ???

Thank you for informing us please.

**Comment by farirat** [comment]
Limits are the hardware limits.

**Comment by ChegMarcoADVANTECH** [comment]
Thank you for your reply.

BUT what kind of materials can you advise us to send to send UNLIMITED SMS ???

What are the specifications of a Linux server to configure Jasmin to successfully send UNLIMITED SMS ???

WHAT KIND of Server or Hardware can help us support the sending of UNLIMITED SMS through Jasmin SMS Gateway ???

Thank you for informing us please.

**Comment by magojr** [comment]
If your question is about the limit of the SPEED of the incoming queue or outgoing queue, as default value they are NOT software limited, you can limit the number of SMS per second for both incoming and outgoing SMPP connection and you can find the parameter to do so in the configuration documentation. You can change them using telnet in your jasmin box as explained in the documentation.
The overall amount of SMS is not limited at all if the machine have enough disk/ram/CPU to contain the SMS flow (space for DLR mapping queue in redis, incoming and outgoing queue in rabbit, but they should be always empty if you does not set any limit), you have to check the "consumed" resources  based on your config and use cases.

So if the question is about the total number of SMS sendable (not SMS/second but total number of SMS), ther's no limit.

If you are asking for an hardware that give you unlimited speed the answer teorically is only one:  UNLIMITED CPU with UNLIMITED frequency, UNLIMITED RAM, UNLIMITED bandwith BUS, UNLIMITED network speed and UNLIMITED disk space with UNLIMITED troughput...

So the software itself hasn't any "license limit" or "default limit" even if I think that your upstream provider surely has a contractual limit configured so you should prefer to limit the amount of message that you pass for each second in order to avoid loosing messages.  You can surely use Jasmin without any software limit at all (at your risk).

A good question to witch I'm also interested is about a "best practice configuration for high troughput" for all the main components: Jasmin, Redis, Rabbit and Linux itself to have the best SMS troughtput from a "standard" hardware.
It may be helpfull to know the real troughtput reachable from a Jasmin node using that configuration with that specific hardware (a kind of benchmark similar to the ones we are used to find in the database world but specific for Jasmin).
This may be usefull to correctly estimate and enumerate the cost of the infrastructure nevertheless anybody should consider the other peer (provider) speed or the network roundtrip time that may decrease the troughtput a lot (IMHO)

**Comment by ChegMarcoADVANTECH** [comment]
Thank you very much for those details. But how to keep "**space for DLR mapping queue in redis, incoming and outgoing queue in rabbit**" always empty ??? 
Are there Linux commands to empty them permanently ???

**Comment by magojr** [comment]
I can't figure out why you should keep all these queues always empty. Let's think about Jasmin like a garden irrigator, you are asking a way to keep the irrigator tubes empty but fload the garden with water so, yes, you can do it tecnically but the irrigator doesn't works in this way. 
Anyway, for Redis, you can set the DLR timeout in jasmin.cfg, every entity in Redis has its own time to live so you can keep it at 1 second and have in redis a very very low amount of data (not sure of the behaviour if you set it to 0). This may be used if the upstream provider does NOT send you any DLR, in the opposite case this will bring your log to be floaded from errors because the DLR that come back does not found any matching entity, so... if you are sure that noone of your provider send you back any DLR, you can decrease the parameter dlr_expiry to 1 second in /etc/jasmin/jasmin.cfg. 
But it's not suggested to do so... 
In order to manually flush the Redis data you have to use a redis client (redis-cli command or a redis GUI like PhpRedisAdmin or any other tool that you like, you can find mor einfo at https://redis.io/documentation).
About Rabbit queues, they are the core of the jasmin flow and they get filled when messages come; next step, they are consumed and moved to the correct outgoing queue (based on routing and outoing connector configured) until they get "consumed" sending out the SMS to the upstream provider. So you cannot keep them always empty if you want that Jasmin works as expected but if you haven't any limit and if the CPU has enough power to send all messages immediatelly and if the upstream provider immediatelly accept them, you should have these queues always filled with few records (the one that are menaged in that moment from Jasmin).
Rabbit has its own web interface to manage it at http://YOURSERVERIP:15672/  when you can flush any queue manually, you can check that here: https://www.rabbitmq.com/documentation.html. 

Important Note: manually work on Redis and Rabbit data bring jasmin not to work as expected so I strongly suggest to work on configuration on jasmin cfg imnstead of manually flush data.

**Comment by chegmarco1989** [comment]
OK.  Thank you again for your answer.  In this case, do you know a host with the following offers that can help me install Jasmin with unlimited sending efficiency.
 Can you recommend a Linux hosting service provider with the following characteristics:

**UNLIMITED CPU with UNLIMITED frequency, UNLIMITED RAM, UNLIMITED bandwith BUS, UNLIMITED network speed and UNLIMITED disk space with UNLIMITED troughput** 

 ???

 Thank you for informing me please.

**Comment by magojr** [comment]
Nobody can have UNLIMITED performance in every HW/SW solution (for what I know), maybe with quantistic computing it will be possible in the future... who knows... but for now, IMHO that's simply not possible.
Are we really loosing time speaking about a way to have unlimited speed?
Do someone ever thought to go to a car seller asking for a car that has no limit in max speed, not the sound speed or the light speed but unlimited... Are you joking?

I was thinking we may be interested to understand how to optimize the settings to get the max possible speed and to have some data about limits achieved with a couple of HW configuration. That may be usefull for estimating, projecting and scaling strategy purpose.

About unlimited speed, I pass, maybe someone with a "more opened" mind than mine may find a solution.

**Comment by chegmarco1989** [comment]
OK.  Thanks for the lighting.  The goal is to send a maximum of SMS in record time and since someone had suggested a Server with unlimited capacities that is why I asked the question to know if you don't know any  unlimited host.

 The idea or the objective is to send several thousand or even millions of SMS with Jasmin.

**Comment by magojr** [comment]
I also sent thousand SMS with jasmin but you cannot think to send them in a second and not to queue them, they are a flow, if you don't queue them, they will be enqueued somewhere else in the sending chain. Jasmin has been made to be one ring of this chain managing flows of thousand and milion of SMS (for what I know, I'm using it I didn't write it) but you usually don't easily found a provider giving you SMPP connection capable of more than 30 / 40 SMS per second, lets say anyway you have an agreement up to 100 SMS/second. 
Your goal may be to send 100 SMS/second. That means 6000 SMS/minute 360.000 SMS/hours 8.640.000 SMS/day. 
We are speaking about a potential traffic cost of about 250.000$/day (it may vary from country, operator, quality ecc) but just to give a "generic cost" to this ... we are speaking of a potential of 7Milions $/month of costs (usually prepaid traffic).
 
So, step 1, you should check the speed that your provider is able to supply you, then you should try to have the HW/software that achieve that speed  **and limit the outgoing speed** to avoid to be throttled (with errors) from the provider (how? queueing SMS if they come faster, waiting to send them respecting the speed supplied from your provider, so this is what jasmin do and why it's strange to ask a way to have empty queues, no memory used, unlimited speed).
Supposing that someone need a (very high) speed (let's say 1000 SMS/second), he is potentially managing a business of 1000Million$/year so he shouldn't be warried about the costs for buy hardware to get 10 (or 100) jasmin boxes.
He can probably easily buy the overall project and hire the people able to rewrite it in the way and for the speed needed.

**Comment by ChegMarcoADVANTECH** [comment]
Ok. Thank you for your various explanations. We understand better.
