### ISSUE TITLE
E: Unable to locate package python-jasmin

### ISSUE THREAD

**Issue by rahcomp** [jookies/jasmin#919]
I have Ubuntu 18.04
Followed the steps provided at https://docs.jasminsms.com/en/latest/installation/index.html#prerequisites-dependencies

Getting following error

root@smpp-dev-nd01:~# sudo apt-get install python-jasmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
**E: Unable to locate package python-jasmin**

**Comment by farirat** [comment]
Due too python2 deprecation in latest Ubuntu releases Jasmin were not packaged for Ubuntu 18.x and 19.x releases.

It is now packaged for Ubuntu 20.04 on python3 (and will be packaged for future Ubuntu releases as well), the package name is renamed to **jasmin-sms-gateway** instead of **python-jasmin**, this is not indicated to date in the documentation, it will be done once Jasmin 0.10.6 is released (we're working on RHEL/CentOS packaging).

**Comment by rahcomp** [comment]
E: Unable to locate package jasmin-sms-gateway

Could you please provide steps here to install on Ubuntu 20.04

**Comment by hzcodertr** [comment]
add skype tarikogut

**Comment by farirat** [comment]
@rahcomp 

1. curl -s https://packagecloud.io/install/repositories/jookies/jasmin-sms-gateway/script.deb.sh | sudo bash
2. apt-get install jasmin-sms-gateway

This is not documented to date.
