### ISSUE TITLE
Interceptor not sending SMS.

### ISSUE THREAD

**Issue by mrsanvicente** [jookies/jasmin#996]
Hello,  

I have a weird situation, where some sms do not pass the interceptor and other ones yes ( i might say the difference is originating phone, destination number is the same, so no routing issue)  ,  I have set the logging to DEBUG or ERROR,   But there is not clue at the interceptor log.

Here i have the DEBUG of a one working and other not working.  Any idea how to do further troubleshooting? The current interceptor does some hlr lookup and ton and npi setting.

Thank you in advance
[interceptor-log.txt](https://github.com/jookies/jasmin/files/6859027/interceptor-log.txt)

**Comment by magojr** [comment]
Hi mrsanvincente,
I noted in your logs that the second TON  is "INTERNATIONAL" and NPI is "ISDN" so the destination_addr should be in international format: +XX.YYYYYYYYYY this may be the issue BUT you wrote the first one is the blocked one... 
In the first one the service type is an empty string instead of None; similar for protocol_id (0 instead of None); even the esm_class is different... but also the field data_coding is 0 in the second one. It should be specified for what I know.
So, it seems that the second message is malformed but you say it go trought...
I suggest you to try checking a single difference at once in order to understand witch one is the cause.

**Comment by mrsanvicente** [comment]
Hi Magojr,

Thanks for taking sometime to look at this case.

I might try to set those smpp fields on the interceptor,  but  i do not have crontrol on the origination setup ( those come from different phones).

-Data_coding works, bu make no difference
   routable.pdu.params['data_coding']  =0

-Trying to se protocol_id to "0" or "None" or None i get the following error:

   routable.pdu.params['protocol_id']  ='None'
   2021-07-22 17:10:39 CRITICAL 6781 Rejecting SubmitSmPDU[13410fd9-8309-42f8-8bdb-2785ac6815ff] through 
   [cid:rodsms] for an unknown error (<type 'exceptions.TypeError'>): %d format: a number is required, not str


So,  What is frustrating is that i dont get any message or error on the interceptor,  it just silently drop the sms...

Any idea?

Thanks

**Comment by magojr** [comment]
The error is because you used the string 'None' instead of the boolean **None**.
For the issue itself there should be something that block the message. If you have no control on the source, you should validate/correct it inside the interceptor, the only suggestion is to try to switch every parameters in the PDU to match the working one, take care of TONS and NPI, of the data coding and every parameter that is not set as the working messages.
If you can achieve the same format, of the working one, you should get the message working.

**Comment by mrsanvicente** [comment]
Hello @magojr 


The strangest thing is when i got a sms going through and other not,  having the same parameters...

I also forgot to mention that the interptor was setting tons and npis and a value on system_type:

routable.pdu.params['service_type']  = anum

After removing the service_type setup it is working fine, without the randon behavior......

So,   Do you think i may use another field to pass the  anum value ( hlr value of anumber).


Thank you for the followup!
Regards
